#服务器的端口号
server:
  port: 8003
eureka:
  instance:
    hostname: 192.168.43.89  #服务器的IP地址
  client:
    serviceUrl:    #注册服务器的地址
      defaultZone: http://192.168.43.183:8000/eureka/
spring:
  application:
    name: publicUserService

    rabbitmq:
      host: 127.0.0.1  #rabbitmq中间件的IP
      port: 5672
      username: admin
      password: admin
      publisher-confirms: true
      publisher-returns: true
      virtual-host: /
      listener:
        simple:
          acknowledge-mode: manual  #开启ACK
  datasource:
    url: jdbc:mysql://cdb-k8anlqni.cd.tencentcdb.com:10151/publicService?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
        ddl-auto: update
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database-platform: org.hibernate.dialect.MySQL5Dialect


