
#服务器的端口号
server:
  port: 8088
#服务器的名字
spring:
  application:
    name: register
  datasource:
    url: jdbc:mysql://localhost:3306/cbd?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 116525
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  instance:
    hostname: 127.0.0.1  #服务器的IP地址
  client:
    registerWithEureka: false  #是否向服务器注册
    fetchRegistry: false
    serviceUrl:    #服务器向外发布的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
