#服务器的端口号
server:
  port: 8003
eureka:
  instance:
    hostname: 127.0.0.1  #服务器的IP地址
  client:
    serviceUrl:    #注册服务器的地址
      defaultZone: http://127.0.0.1:8088/eureka/
spring:
  application:
    name: frontService
  datasource:
    url: jdbc:mysql://localhost:3306/cbd?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 116525
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate:
      enable_lazy_load_no_trans: true
      ddl-auto: update
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform: org.hibernate.dialect.MySQL5Dialect

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8




#ribbon:
#  eureka:
#    enabled: true
